Issue99 artist clicked
Makes-Innovation-Hub/harmony pull request #128
Opened 2023-06-13 10:16 UTC by daniahih

2023-06-13 12:13 UTC, yishain11 requested changes

2023-06-13 12:13 UTC, yishain11 commented on client/src/components/TopSongGallary/ImageBoxWithDetails.jsx
> +      const response = await axios.get(
remove to slice and use rtk query, plus you can use fetch, no need to add axios

2023-06-18 10:16 UTC, yishain11 requested changes

2023-06-18 10:16 UTC, yishain11 commented on server/server.js
> +app.use("/api/v1/artist", artistSearchRoute);
add this to artists route

2023-06-18 16:06 UTC, daniahih commented on server/server.js
> +app.use("/api/v1/artist", artistSearchRoute);
done

2023-06-19 18:50 UTC, merged