Lyrics#4
Makes-Innovation-Hub/harmony pull request #26
Opened 2023-05-14 16:30 UTC by userisash

2023-05-14 17:17 UTC, yishain11 requested changes

2023-05-14 17:17 UTC, yishain11 commented on client/package.json
> +    "react-icons": "^4.8.0"
you have a bug here. add trailing coma

2023-05-14 17:17 UTC, yishain11 commented on client/package.json
> +    "@iconify/icons-mdi": "^1.2.45",
remove, use figma icons

2023-05-14 17:17 UTC, yishain11 commented on client/src/Components/HeadStyles.jsx
> +  @import url('https://fonts.googleapis.com/css2?family=ABeeZee:ital@0;1&display=swap');
download font to assetes and load from there, sometimes we will not have good connection, and this will take time

2023-05-14 17:17 UTC, yishain11 commented on client/src/components/Lyrics.jsx
> +const LyricsSection = styled.section`
put all styles in a seperated file. if its 1 - it can be in the same file, if it more - move it

2023-05-20 21:16 UTC, yishain11 requested changes
still looks very diff from figma!

2023-05-21 09:14 UTC, yishain11 requested changes
please move the lyrics component from the home component to the song page

2023-05-21 10:15 UTC, userisash commented
> please move the lyrics component from the home component to the song page

2023-05-21 11:16 UTC, yishain11 requested changes

2023-05-21 11:16 UTC, yishain11 commented on client/src/components/Lyrics.jsx
> +          Lorem ipsum dolor sit amet consectetur adipisicing elit.
this is hard coded. think that you get a single text with all the lyrics - and you need to present them.
build the component to handle that

2023-05-23 09:29 UTC, merged