Not-found-animation + Translating-animation + text #18 #20
Makes-Innovation-Hub/harmony pull request #27
Opened 2023-05-14 18:01 UTC by ArturLabenskyy

I finished 2 components for "Translating text" and "Not Found" with text for each one.

2023-05-14 18:49 UTC, ArturLabenskyy commented
got 62 conflicts at package-lock.json 😥

2023-05-15 08:45 UTC, yishain11 requested changes

2023-05-15 08:45 UTC, yishain11 commented on client/package.json
>      "npm": "^9.6.6",
remove npm

2023-05-15 08:52 UTC, ArturLabenskyy commented on client/src/App.css
>  .logo {
On the main branch, in App.jsx file there no import for App.css

2023-05-15 14:01 UTC, ArturLabenskyy commented
I made refactoring to Animation component so it possible to reuse it for both animations with text: NotFoundAnimation and TranslatingAnimation

2023-05-16 14:47 UTC, yishain11 commented on client/src/components/Animation/Animation.styled.js
> +    // Small screen + Laptop screen
remove - we work obly with mobile

2023-05-16 14:47 UTC, yishain11 commented on client/src/components/Animation/Animation.styled.js
> +    //  Desktops + large screen
remove - we work obly with mobile

2023-05-16 14:47 UTC, yishain11 commented on client/src/components/Animation/Animation.styled.js
> +    // Extra large + TV screen
remove - we work obly with mobile

2023-05-16 19:33 UTC, yishain11 requested changes

2023-05-16 19:33 UTC, yishain11 commented on client/src/App.css
>  .logo {
its up to you and toni - if you use app.css - remove all the unrelevant classes and animations.
if you don't need it - delete the file and remove the import
currnlty you have a mix of both - vite classes and your styling

2023-05-17 09:13 UTC, ArturLabenskyy commented on client/src/App.css
>  .logo {
App.css changed

2023-05-17 10:49 UTC, ArturLabenskyy commented
Conflicts resolved

2023-05-17 12:28 UTC, yishain11 requested changes
fix home page. in main it looks ok - with the headr at the top, and in your branch its messed

2023-05-18 11:14 UTC, ArturLabenskyy commented
Waiting for approve

2023-05-20 21:13 UTC, yishain11 requested changes
header is still bad in your branch

2023-05-21 11:44 UTC, yishain11 requested changes

2023-05-21 11:44 UTC, yishain11 commented on client/package.json
> +        "parse-conflict-json": "^3.0.1",
are you using this?
if yes - should it be as dependancy or as dev dependancy?

2023-05-21 11:44 UTC, yishain11 commented on client/src/App.css
> +    padding: 2rem;
this messes the style in other pages

2023-05-21 11:51 UTC, ArturLabenskyy commented on client/src/App.css
> +    padding: 2rem;
Fixed

2023-05-23 07:36 UTC, yishain11 requested changes

2023-05-23 07:36 UTC, yishain11 commented on client/src/components/Tagline/Tagline.styled.js
> +import { styled } from 'styled-components'
this cuases an error. fix it

2023-05-23 12:07 UTC, merged